name: 'PR Analyser'

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Analyse PR Changes with AI'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get PR Files
        id: pr_files
        run: |
          PR_FILES=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            | jq -r '.[].filename' | paste -sd "," -)
          echo "PR_FILES=$PR_FILES" >> $GITHUB_ENV

      - name: Analyze Each File
        env:
          COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_MODEL: ${{ vars.OLLAMA_MODEL }}
          PR_FILES: ${{ env.PR_FILES }}
        run: |
          echo "Processing files: $PR_FILES"
          IFS=',' read -ra FILES_ARRAY <<< "$PR_FILES"
          for FILE_INFO in "${FILES_ARRAY[@]}"; do
            FILE=$(echo "$FILE_INFO" | cut -d':' -f1)
            COMMIT_ID=$(echo "$FILE_INFO" | cut -d':' -f2)
            echo "Adding comment to file: $FILE at commit: $COMMIT_ID"
          
            # Placeholder: Define the position in the diff
            POSITION=1  # Update logic to calculate actual diff positions
          
            # Construct the comment body
            COMMENT_BODY="**Changes in ${FILE}:**\n\n* [Your AI-based analysis or comment here]*"
          
            # Call GitHub API to post a comment
            curl -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "$(jq -n --arg body "$COMMENT_BODY" \
                          --arg path "$FILE" \
                          --arg commit_id "$COMMIT_ID" \
                          --argjson position $POSITION \
                          '{body: $body, path: $path, commit_id: $commit_id, position: $position}')" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments"
          done
