name: 'PR Analyser:'

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Analyse PR Changes with AI:'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: pr_diff
        run: |
          # Fetch the PR diff
          PR_DIFF=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            | jq -r '.[] | .patch' | tr '\n' ' ')

          echo "PR Diff: $PR_DIFF"
          echo "PR_DIFF=$PR_DIFF" >> $GITHUB_ENV

      - name: Send PR Changes to Ollama API for Analysis
        env:
          COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DIFF: ${{ env.pr_diff }}
          OLLAMA_MODEL: ${{ vars.OLLAMA_MODEL }}  # Use the variable here
        run: |
            # Construct the prompt for Ollama to analyze the PR diff
            INSTRUCTION="Check provided TypeScript code and propose improvements of this code. Code:\n\n$PR_DIFF"
            
            # Send POST request with the PR diff and instructions to Ollama API
            RESPONSE=$(curl -s -w "%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -d "{
                    \"model\": \"$OLLAMA_MODEL\",
                    \"prompt\": \"$INSTRUCTION\",
                    \"options\": {
                      \"temperature\": 0.7
                    },
                    \"stream\": false
                  }" \
              https://ai-agent-yz.rpplabs.com/api/generate)
            
            # Extract status code and response body
            HTTP_STATUS="${RESPONSE: -3}"
            RESPONSE_BODY="${RESPONSE%???}"
            
            echo "HTTP Status: $HTTP_STATUS"
            echo "Response Body: $RESPONSE_BODY"
            
            # Determine comment content based on HTTP status
            if [ "$HTTP_STATUS" -eq 200 ]; then
              COMMENT_BODY=$(echo "$RESPONSE_BODY" | jq -r '.response' | jq -Rs .)
            else
              COMMENT_BODY="AI agent encountered an issue."
            fi
            
            # Post the result as a comment on the PR issue
            curl \
              -X POST \
              $COMMENTS_URL \
              -H "Content-Type: application/json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"body\": $COMMENT_BODY}"
